version: '3'
services:
  api-server:
    image: api-server
    ports:
      - '8080:8000'
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    networks: 
      - skynet
  task-server:
    image: task-server
    links:
      - redis
      - api-server
    environment:
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    networks: 
      - skynet
  redis:
    image: 'redis:4.0.11'
    networks: 
      - skynet

networks:
  atlan:
    driver: "bridge"